<?xml version="1.0" encoding="utf-8"?><Database Class="EDiaryContentDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="User">
    <Type Name="User">
      <Column Member="ID" Type="System.Int32" CanBeNull="false" />
      <Column Member="PWD" Type="System.String" CanBeNull="false" />
      <Column Member="Name" Type="System.String" CanBeNull="false" />
      <Column Member="Remarks" Type="System.String" CanBeNull="false" />
      <Association Name="User_Diary" Member="Diary" ThisKey="ID" OtherKey="UserID" Type="Diary" />
    </Type>
  </Table>
  <Table Name="" Member="Diary">
    <Type Name="Diary">
      <Column Member="UserID" Type="System.Int32" CanBeNull="false" />
      <Column Member="Datetime" Type="System.DateTime" CanBeNull="false" />
      <Column Member="Title" Type="System.String" CanBeNull="true" />
      <Column Member="Content" Type="System.String" CanBeNull="false" />
      <Column Member="DiaryPWD" Type="System.String" CanBeNull="true" />
      <Column Member="Visible" Type="System.Boolean" CanBeNull="false" />
      <Association Name="User_Diary" Member="User" ThisKey="UserID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>